### ISSUE TITLE
Migrate from Sass to pure CSS due to node-sass deprecation

### ISSUE THREAD

**Issue by otegami** [ranguba/ranguba#35]
Migrate our stylesheets from Sass (SCSS) to pure CSS in order to remove the deprecated `node-sass` dependency.

## Background
The `node-sass` package has been deprecated. Continuing to use deprecated dependencies can lead to security vulnerabilities and maintenance issues. We will migrate it to standard CSS.
- Remove the need for deprecated `node-sass`
- Simplify our build process

ref: https://github.com/sass/node-sass

## TODO

- [x] Rewrite style format from Sass to CSS
- [x] Change the file extension
- [x] Remove `sass-rails`
